export const BATCH_UPDATE_BIDS_AND_ASKS_DATA = 'BATCH_UPDATE_BIDS_AND_ASKS_DATA';
export const TOGGLE_PRODUCT_GROUP = 'TOGGLE_PRODUCT_GROUP';
export const RESET_BIDS_AND_ASKS_DATA = 'RESET_BIDS_AND_ASKS_DATA';
export const WEBSOCKET_SEND_SUBSCRIBE_MESSAGE = 'WEBSOCKET_SEND_SUBSCRIBE_MESSAGE';
export const WEBSOCKET_SEND_UNSUBSCRIBE_MESSAGE = 'WEBSOCKET_SEND_UNSUBSCRIBE_MESSAGE';
